### ISSUE TITLE
Could you please tell me are they duplicate or not, thanks.

### ISSUE THREAD

**Issue by liamxg** [hongsamL/travHistProtocol#1]
![image](https://user-images.githubusercontent.com/46078579/114297789-50e05700-9ae5-11eb-8c5a-81d63239c150.png)

**Comment by liamxg** [comment]
for 282_GISAID_sarscov2_travelHist_masked.xml file, thanks.

**Comment by hongsamL** [comment]
They are not duplicates, both are required for the analysis.
